# Generated by Django 3.2.5 on 2021-07-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ctrlf_auth", "0002_emailauthcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("is_approved", models.BooleanField(default=False)),
                ("request_contents", models.CharField(max_length=300)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ctrlf_auth.ctrlfuser")),
            ],
        ),
    ]
