# Generated by Django 3.2.5 on 2021-08-08 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlf_auth", "0003_auto_20210808_0110"),
        ("ctrlfbe", "0002_auto_20210808_0110"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sub_id", models.IntegerField(help_text="type에 대한 id")),
                (
                    "type",
                    models.CharField(
                        choices=[("NOTE", "노트"), ("TOPIC", "토픽"), ("PAGE", "페이지")],
                        help_text="NOTE, TOPIC, PAGE",
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("CREATE", "생성"), ("UPDATE", "수정"), ("DELETE", "삭제")], help_text="CRUD", max_length=30
                    ),
                ),
                ("reason", models.TextField(default="", help_text="수정 혹은 삭제 이유")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="수정 혹은 삭제의 주체자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ctrlf_auth.ctrlfuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="issue",
            name="content_history",
        ),
        migrations.DeleteModel(
            name="ContentHistory",
        ),
        migrations.AddField(
            model_name="issue",
            name="content_request",
            field=models.ForeignKey(
                help_text="content 생성/수정/삭제 요청",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ctrlfbe.contentrequest",
            ),
        ),
    ]
