# Generated by Django 3.2.5 on 2021-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0004_pagecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
