# Generated by Django 3.2.5 on 2021-10-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0005_page_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="summary",
            field=models.CharField(default="", max_length=300),
        ),
    ]
