# Generated by Django 3.2.4 on 2021-11-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0006_page_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="page",
            name="owners",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="owners",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="title",
        ),
        migrations.AlterField(
            model_name="page",
            name="summary",
            field=models.CharField(default="", help_text="이슈의 content에 해당하는 내용", max_length=300),
        ),
    ]
