# Generated by Django 3.2.4 on 2021-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlf_auth", "0003_auto_20210808_0110"),
        ("ctrlfbe", "0007_auto_20211103_2059"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="owners",
            field=models.ManyToManyField(to="ctrlf_auth.CtrlfUser"),
        ),
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="owners",
            field=models.ManyToManyField(to="ctrlf_auth.CtrlfUser"),
        ),
        migrations.AddField(
            model_name="topic",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
