# Generated by Django 3.2.4 on 2021-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0008_auto_20211103_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="page",
            name="summary",
            field=models.CharField(default="", max_length=300),
        ),
    ]
