# Generated by Django 3.2.4 on 2021-11-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0009_auto_20211103_2105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="summary",
            field=models.CharField(default="", help_text="이슈의 content에 해당하는 내용", max_length=300),
        ),
    ]
