# Generated by Django 3.2.4 on 2021-11-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0009_auto_20211106_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="action",
            field=models.CharField(
                choices=[("CREATE", "생성"), ("UPDATE", "수정"), ("DELETE", "삭제")],
                default="",
                help_text="CRUD",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="related_model_id",
            field=models.IntegerField(default=1, help_text="note_id, topic_id, page_id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="issue",
            name="related_model_type",
            field=models.CharField(
                choices=[("NOTE", "노트"), ("TOPIC", "토픽"), ("PAGE", "페이지")],
                default="NOTE",
                help_text="NOTE, TOPIC, PAGE",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
