# Generated by Django 3.2.5 on 2021-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0010_auto_20211106_1408"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="related_model_id",
            field=models.IntegerField(default=0, help_text="note_id, topic_id, page_id"),
        ),
    ]
