# Generated by Django 3.2.4 on 2021-11-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0010_alter_page_summary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageComment",
        ),
    ]
