# Generated by Django 3.2.4 on 2021-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0011_delete_pagecomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="content",
            new_name="reason",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="content_request",
        ),
        migrations.AddField(
            model_name="issue",
            name="action",
            field=models.CharField(
                choices=[("CREATE", "생성"), ("UPDATE", "수정"), ("DELETE", "삭제")],
                default="",
                help_text="CRUD",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="content_type",
            field=models.CharField(
                choices=[("NOTE", "노트"), ("TOPIC", "토픽"), ("PAGE", "페이지")],
                default="",
                help_text="NOTE, TOPIC, PAGE",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ContentRequest",
        ),
    ]
