# Generated by Django 3.2.5 on 2021-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0011_alter_issue_related_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="etc",
            field=models.CharField(help_text="legacy title을 저장하는 용도 및 다양하게 사용", max_length=300, null=True),
        ),
    ]
