# Generated by Django 3.2.4 on 2021-12-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0012_issue_etc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="summary",
        ),
    ]
