# Generated by Django 3.2.4 on 2021-11-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0012_auto_20211103_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="content_id",
            field=models.IntegerField(default=0, help_text="note_id, topic_id, page_id"),
        ),
    ]
