# Generated by Django 3.2.4 on 2021-11-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0013_issue_content_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="summary",
        ),
    ]
