# Generated by Django 3.2.4 on 2021-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0015_pagehistory_version_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagehistory",
            name="version_type",
            field=models.CharField(choices=[("CURRENT", "최신"), ("UPDATE", "수정요청"), ("PREVIOUS", "과거")], max_length=30),
        ),
    ]
