# Generated by Django 3.2.4 on 2021-12-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlfbe", "0016_alter_pagehistory_version_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="page",
            name="title",
        ),
        migrations.AlterField(
            model_name="issue",
            name="related_model_id",
            field=models.IntegerField(default=0, help_text="note_id, topic_id, page_history_id"),
        ),
        migrations.AlterField(
            model_name="pagehistory",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="page_history", to="ctrlfbe.page"
            ),
        ),
    ]
