# Generated by Django 3.2.5 on 2021-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CtrlfUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "email",
                    models.EmailField(help_text="email 주소", max_length=255, unique=True, verbose_name="email address"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="패스워드")),
                ("nickname", models.CharField(help_text="닉네임", max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
