# Generated by Django 3.2.5 on 2022-03-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctrlf_auth", "0003_auto_20210808_0110"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctrlfuser",
            name="is_admin",
            field=models.BooleanField(default=False, help_text="관리자 여부"),
        ),
    ]
