# Generated by Django 2.0.13 on 2021-06-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create_date",
            new_name="created_date",
        ),
    ]
